### ISSUE TITLE
click button does not work on chromecast 4k control- Android 12

### ISSUE THREAD

**Issue by Litorti** [virresh/matvt#55]
Hello this issue is for Android 12 update

**Comment by Jooose25** [comment]
Tengo el mismo problema con la última actualización a Android 12

**Comment by andresflorentin** [comment]
Yo también tengo el mismo problema, no funciona el mouse matvt en el chromecast 4 Google tv con Android 12

**Comment by Nardokrazy2x** [comment]
I am also having this issue

**Comment by virresh** [comment]
Hi,
Thanks for reporting.
Can someone send a log report for me to look at?
I don't have a chromecast and can't deduce what the issue is by the above comments.

**Comment by Tbo29** [comment]
Yes, click only works if the item you want to click has focus.

**Comment by andresflorentin** [comment]
Button click and scroll mode don't work

**Comment by RNavarro3000** [comment]
I have an Onn 4k device running Android 12 with the same problem as OP.  Here is logcat output with just the MATVT info.
[logcat.txt](https://github.com/virresh/matvt/files/9926095/logcat.txt)

**Comment by virresh** [comment]
Thanks @RNavarro3000 for the log. I can see events being read just fine. I suppose this is a problem at kernel level of discarding click events that did not come from system itself. 


Can you try looking at the other logs and see if you see any warnings from the kernel about rejecting input or something.
Also, I have a beta version that uses ADB instead of accessibility service - https://github.com/virresh/matvt/releases/tag/v1.06-pre-release

It's not pretty, but it should work as a stop-gap. I don't see how it can be improved in user experience though.

**Comment by Tbo29** [comment]
Sorry to say, the beta adb release also does not work. Tried with a bluetooth mouse connected. Also does not click. Doesn't look too good.

**Comment by RNavarro3000** [comment]
@virresh  Attached is unfiltered logcat output from another event.  If this doesn't help, let me know specifically what files or output you need captured as I'm not too familiar where Android keeps things.
[logcat2.txt](https://github.com/virresh/matvt/files/9956162/logcat2.txt)

**Comment by virresh** [comment]
Thanks @RNavarro3000 
I see the logs are for official release version. They show similar symptoms to what I saw when Android 11 was released, although @Tbo29 mentioned that that the ADB version isn't working either. In the logs, MATVT is able to read views from the screen just fine, but the input events fail and get eaten up (as if the gesture dispatch api didn't exist at all).

Can one of you also give logs for the adb version if possible?

**Comment by st-ivan** [comment]
> Thanks @RNavarro3000 I see the logs are for official release version. They show similar symptoms to what I saw when Android 11 was released, although @Tbo29 mentioned that that the ADB version isn't working either. In the logs, MATVT is able to read views from the screen just fine, but the input events fail and get eaten up (as if the gesture dispatch api didn't exist at all).
> 
> Can one of you also give logs for the adb version if possible?

Hi, just tried the adb version and its not working. Id be happy to provide logs if you tell me how to export them.

**Comment by RNavarro3000** [comment]
@virresh   Installed the ADB version and click button is working OK for me now on LineageOS Android TV 12.  Attached is logs for the session, maybe it will help with diagnosing the official release version.

[logcat3.txt](https://github.com/virresh/matvt/files/9999946/logcat3.txt)

https://user-images.githubusercontent.com/121646/201586325-dbeabd38-4047-43da-9135-9aeabd8f983a.mp4

**Comment by titti2000** [comment]
Hi all, I have the same problem on the new Chromecast hd, even with the ADB version; the click works only on what is already selected. I'd like to help you with the log, but I don't know how to do it; No debug app appears in developer options.

**Comment by st-ivan** [comment]
> Seems that ADB is the way to go. The dev from tvQuickActions released an update (2.9.2) which uses ADB to fix the mouse toggle on Android TV 12. Regretfully I don't have it, but users confirmed that the mouse toggle from tvQuickActions is working now on the Chromecast with Google TV and the latest update. Let's see if the dev from Zank Remote will release an update soon, as he said he found the solution.

thanks for the info. Link to the 2.9.2 version pleae? i just found out about this app and seems very helpful, if it works fine i may even buy it.

**Comment by Tbo29** [comment]
It's on the Playstore. Thinking of buying it too. Only $2.0. I have an older version. Works better than Button Mapper.

**Comment by st-ivan** [comment]
> It's on the Playstore. Thinking of buying it too. Only $2.0. I have an older version. Works better than Button Mapper.

thanks.. yeah talked to the developer via telegram, he says it works 100% confirmed. So im buying it. Not only bc of the mouse toggle feature but the 1 button (5 functions) mann thats a game changer for ccwgtv

**Comment by st-ivan** [comment]
ended up buying tvQuickActions which has lots of more features and mouse toggle works .

**Comment by Tbo29** [comment]
> ended up buying tvQuickActions which has lots of more features and mouse toggle works .

Bluetooth Keyboard and Mouse from phone also does work latest version. Means that devs are finding the solution.

**Comment by virresh** [comment]
Thanks for the logs folks!

I got time today to test out the official Google TV emulator image for Android 12, and I found the issue.

The problem is caused because of a fancy new security feature on Android 12+. Explained in detail - https://medium.com/androiddevelopers/untrusted-touch-events-2c0e0b9c374c

I will be updating the official version with a fix for the same and this should work without the ADB. Thanks for your patience, will update here to test out the fix.

**Comment by virresh** [comment]
Please test https://github.com/virresh/matvt/releases/tag/v1.0.7-pre and let me know if this solves problems on Android 12 (click and scroll should now be working).

Based on feedback, I'll add this along with a couple other planned features and release v1.0.7.

**Comment by dikodahan** [comment]
Hey @virresh 
I just tested it on an android 11 TV box and I am still having the same issue.
No problem with getting it to work and show the mouse on screen, however, the "Select" button does not seem to take effect...
I also noticed that when switching to scroll mode it did not scroll the screen for me.

**Comment by virresh** [comment]
@dikodahan pls note this is only for Android 12
For Android 11, you'll have to use the adb version. There is a known issue (only in Android 11) which has been fixed in subsequent versions.

**Comment by Litorti** [comment]
Click only works if focused. Scroll doesn't work

**Comment by dikodahan** [comment]
> @dikodahan pls note this is only for Android 12
> For Android 11, you'll have to use the adb version. There is a known issue (only in Android 11) which has been fixed in subsequent versions.

Hey @virresh 
Thanks for the reply. As stated in your notes for that release, it is EXTREMELY buggy. The once enabled ADB permissions for it, even with mouse not enabled, the D-Pad mode is jumpy and to be almost unusable. The only option to bring the system back to normal operation is to uninstall that version. If you're planning to release an updated 1.07 version, I am happy to test an ADB version of it on Android 11. The current one is not usable.

Again, thanks for all the effort into this project!

**Comment by sujhran** [comment]
> 

Hi @virresh

I have tested 1.0.7 on google chromecast 12 and response is same. Click mouse click didn't work, however it only work for the selected item. For example if i am on the setting tab and if i turned on the toggle and click. it will work one time for the selected item but then didn't work.

So i can say that it is the same experience like 1.0.6.

**Comment by dikodahan** [comment]
> Hi @virresh
> 
> I have tested 1.0.7 on google chromecast 12 and response is same. Click mouse click didn't work, however it only work for the selected item. For example if i am on the setting tab and if i turned on the toggle and click. it will work one time for the selected item but then didn't work.
> 
> So i can say that it is the same experience like 1.0.6.

BTW, Unrelated to the above issue I mentioned on Android 11, I also tested on my Google Chromecast with Google TV with the updated Android 12 version and I am also getting the same as @sujhran with the 1.07 version. Click and scroll did not work for me.

**Comment by sujhran** [comment]
Hi @virresh , please let me know if more information is required to fix the mouse click issue for chromecast android 12. I have two devices, and I can be part of UAT.

**Comment by linekona** [comment]
> > 
> 
> Hi @virresh
> 
> I have tested 1.0.7 on google chromecast 12 and response is same. Click mouse click didn't work, however it only work for the selected item. For example if i am on the setting tab and if i turned on the toggle and click. it will work one time for the selected item but then didn't work.
> 
> So i can say that it is the same experience like 1.0.6.

I have same issue on CCWGTV running Android 12.  Still not working.

**Comment by TerryUK** [comment]
Ditto with the pre release of 1.07. Any news.

**Comment by virresh** [comment]
Ah okay. That's unfortunate.
I don't have actual hardware to test on so don't think I'll be able to uncover any more secrets about this just from the emulator image. Already did the fixes required to get it running on official Google TV Android 12 emulator image (AOSP TV x86 image, May 1 2022 security patch, 5.10.66 kernel version released on 10th Dec 2021). Mentioned the full version and kernel details just in case it rings any bells to anyone.

If anyone has ready access to an Android emulator image that replicates the issue that'll be extremely helpful.

Apart from that, if anyone here can get full logs for the 1.0.7-prerelease version (including system events) from actual hardware that displays the problem, that'll be much appreciated too. (Even better if anyone has ideas on what other security policies were introduced and which other one might be interfering).

**Comment by TerryUK** [comment]
I got TVQuickActions to work but needed quite a bit of Googling to set it up. Mouse movement is jumpy left to right on ES Explorer causing to to page. You have to take it slowly. So even that isn't perfect but handy when you need the odd click on an item.

Virresh you need to splash out on the device.

**Comment by virresh** [comment]
> Virresh you need to splash out on the device.

The project itself doesn't generate any revenue. It is not just free, but open source as well.
Also, a not-so-popular fact is that I've already had people stealing this open-source project and selling it to innocent folks who need it without any credit, framing the open-source project as fake / pirated in the past. 

Even if I fund this project by myself for this one purchase, I can't possibly keep doing it for all future releases of Android sustainably. I don't need so many Android TVs (and they're pretty expensive around my area as well).
I'm happy to volunteer my free time to this project though as I built it out of passion for tinkering and technology.

**Comment by TerryUK** [comment]
👍one guy on a Chromecast Google TV channel on YouTube claims his guy is working with you. Least in the video seems he's the one to investigate for you. The video doesn't currently doesnt work due to the issue.... so his guy needs to talk to you. "Swing Wolf" seems to be the guys name.

https://m.youtube.com/watch?v=UC7bPw2tG4c

**Comment by virresh** [comment]
That's TDUK's channel and I believe you're referring to SweenWolf.

I'm not sure if @sweenwolf gets any compensation for his contributions and is the content creator's "guy". 
The fact is we met on XDA forums and he took interest in this project and contributed a few features (you can see exactly who contributed what here - https://github.com/virresh/matvt/commits/master, and I have appropriately credited every person involved in the credits section here - https://github.com/virresh/matvt#credits).

To be clear, I've requested TDUK to be explicit about the fact that they are just curating knowledge about an open source project and this is not sponsored by them. Have also asked them over an email to at least put a reference to the project (which they replied they've put up somewhere on their website).

It's unfortunate this looks like how it is though, but to be absolutely explicit, the only conversations regarding this project ongoing are all listed as issues on this repository. I've tried [commenting on the YT video](https://www.youtube.com/watch?v=UC7bPw2tG4c&lc=Ugx0dqNStnnkN27LccZ4AaABAg) with updates but my comments on the [followup video](https://www.youtube.com/watch?v=CGxkV0ZIutc) end up getting deleted (probably some spam filter because I don't comment much?) so I've stopped bothering.

**Comment by TerryUK** [comment]
Fingers crossed you will get some assistance.

**Comment by Tbo29** [comment]
[Log_2022-12-04_16-24-33.txt](https://github.com/virresh/matvt/files/10149512/Log_2022-12-04_16-24-33.txt)

Hi virresh. I did a specific log for matvt. Was not so easy as the app for logging was not suited for the Chromecast with Google TV.
However here it is.

When activating scrolling, it does not issue any event. Only when I click. Maybe this log could be usefull.

Btw the Android TV 12 image you have differs from the real Android TV 12 on the CCWGTV. That's why you app works onit and not on the real device.

**Comment by minimeh** [comment]
> That's TDUK's channel and I believe you're referring to SweenWolf.
> 
> I'm not sure if @sweenwolf gets any compensation for his contributions and is the content creator's "guy". The fact is we [met on XDA forums](https://forum.xda-developers.com/t/app-mod-cast-jiotv-mod-with-miracast-android-tv-and-firestick-support.3857654/post-84479545) and he took interest in this project and contributed a few features (you can see exactly who contributed what here - https://github.com/virresh/matvt/commits/master, and I have appropriately credited every person involved in the credits section here - https://github.com/virresh/matvt#credits).
> 
> To be clear, I've requested TDUK to be explicit about the fact that they are just curating knowledge about an open source project and this is not sponsored by them. Have also asked them over an email to at least put a reference to the project (which they replied they've put up somewhere on their website).
> 
> It's unfortunate this looks like how it is though, but to be absolutely explicit, the only conversations regarding this project ongoing are all listed as issues on this repository. I've tried [commenting on the YT video](https://www.youtube.com/watch?v=UC7bPw2tG4c&lc=Ugx0dqNStnnkN27LccZ4AaABAg) with updates but my comments on the [followup video](https://www.youtube.com/watch?v=CGxkV0ZIutc) end up getting deleted (probably some spam filter because I don't comment much?) so I've stopped bothering.

@virresh: TDUK has a habit of saying that "his guy" or "his programmer" is working on his behalf. Even @sweenwolf has made clarifications that he is not TDUK's programmer. This guy just scours the internet and conscripts other's work, sometimes rebranding it, and offering it as his product.

But anyway, with regards to the mouse-click issue on CCGTV in Android 12: I have identified the reason for it and a work-around. It's not just something with your app, but actually every app and any mouse, even mice physically connected using USB or Bluetooth connections.

Refer to the following for details:
`https://developer.android.com/about/versions/12/behavior-changes-all#untrusted-touch-events`

To restore mouse functionality:
```
# A specific app
adb shell am compat disable BLOCK_UNTRUSTED_TOUCHES com.example.app

# All apps
# If you'd still like to see a Logcat message warning when a touch would be
# blocked, use 1 instead of 0.
adb shell settings put global block_untrusted_touches 0
```
I haven't actually tried this with your app, but I can vouch that my Bluetooth mouse works normally after using the above adb command for all apps.

Before I got a Bluetooth mouse, your app saved my bacon and allowed me to use apps that absolutely require a mouse for some things. For that I thank you and really appreciate your great work!

**Comment by virresh** [comment]
Thanks @minimeh 
That is indeed exactly the problem for which I've made the cursor sufficiently transparent to pass the trust threshhold.

Disabling the trust checks altogether would work for sure!
In case anyone on this thread wants to try out what `minimeh` is suggesting, following is the command to disable trust check only for MATVT 1.0.7-pre:
```
adb shell am compat disable BLOCK_UNTRUSTED_TOUCHES io.github.virresh.matvt
```
and they've already mentioned disabling the trust check globally.

I'm looking into a more longer term solution as I feel most ppl wouldn't bother doing this.


@Tbo29 thanks for the log, but they seem to be missing startup logs (e.g [this one](https://github.com/virresh/matvt/blob/master/app/src/main/java/io/github/virresh/matvt/view/OverlayView.java#L45)) and system logs (like `Untrusted touch due to occlusion by`)

And yes, I'm aware the image I'm using might not be exactly same as the commercial version, and probably will never be because every manufacturer has their own different image which is proprietary and cannot be accessed easily, but if there is any open source equivalent of the CCGTV image, that'll be more helpful.

**Comment by virresh** [comment]
Folks, can someone test with https://github.com/virresh/matvt/releases/download/v1.0.7-pre/matvt-app-release-1.0.7-pre2.apk ?

This has a different set of fixes for the android platform trust issues. This also has more advanced and detailed logs, so hoping to get more information from them.

**Comment by TerryUK** [comment]
On pointers TVQuickActions uses a blob not an arrow, very similar to the Android TV Downloader app. Good enough I reckon rather than a pointer least for a TV screen.

**Comment by kokotas89** [comment]
Tried the latest pre release on ccwgtv on Android tv os 12 but unfortunately nothing's changed. Scrolling and clicking still not working.

**Comment by sujhran** [comment]
I have tried 1.0.7 Pre 2 apk on chromecast 4K Android 12 so this time mouse click does not work at all. In previous release we were able to click one time on the selected  tab but if we move mouse doesn't click anywhere else.

**Comment by virresh** [comment]
Unfortunate.

The pointers in matvt are customisable, so you can use the orb if you want instead of pointer.

I have removed the fallback click mechanism due to which clicking on focused elements no longer works.

Could someone post logs as well?

**Comment by kokotas89** [comment]
Here are the logs from my device. Hope it helps you out.
[logcat.txt](https://github.com/virresh/matvt/files/10169132/logcat.txt)

**Comment by sujhran** [comment]
Can someone help me, how to get the logs from chromecast 4k (google TV).

I feel like I am lost.

**Comment by kokotas89** [comment]
@sujhran You basically connect to your chromecast remotely via ADB and write the logcat info to your PC or phone. 

adb connect 192.168.X.X:5555 (chromecast's IP address)
adb -s 192.168.X.X:5555 logcat -d > /sdcard/logcat.txt

I won't get into specifics here but you can look up adb network debugging to figure it out.

**Comment by dikod** [comment]
Hey @virresh 
Does it make sense for you to add a "Export logs" option in the configuration section?
This way you can make sure it exports all required log items. If it's multiple log files, you can also zip them together to a single file. You can just save it to the downloads folder so it's easy to pull the file and add it here.

Just trying to make sure you have more people helping out with easy access to all the info you need to troubleshoot.

**Comment by virresh** [comment]
Thanks a ton @kokotas89 ,
Those are exactly the one's I was hoping to get.

After going through them, one last thing -
Can you run `adb shell pm list features` and share it's output?

My primary suspect is that the device would declare not to support `feature:android.hardware.faketouch` or `feature:android.hardware.touchscreen` in it. If this is the case, our next best bet would be some fixes in adb-based engine (or some hacks to make the TV report that it has this feature).

**Comment by virresh** [comment]
> "Export logs" option in the configuration section

Thanks for the suggestion @dikod 
I hadn't really thought about it, but now that I do think about it, looks like this won't suffice either. Android apps are sandboxed usually and I would not be able to export any System level logs from within the app itself. Would need an external hook like another PC or something. I think there are some hacks that will help me get the logs, but not trivial for now (especially with increased security features being launched with every release).

**Comment by kokotas89** [comment]
My pleasure @virresh! Glad you got the output you wanted. Here's the ccwgtv android 12 feature list:

feature:reqGlEsVersion=0x30002
feature:android.hardware.audio.output
feature:android.hardware.bluetooth
feature:android.hardware.bluetooth_le
feature:android.hardware.ethernet
feature:android.hardware.gamepad
feature:android.hardware.hardware_keystore=100
feature:android.hardware.hdmi.cec
feature:android.hardware.location
feature:android.hardware.location.network
feature:android.hardware.opengles.aep
feature:android.hardware.ram.normal
feature:android.hardware.screen.landscape
feature:android.hardware.security.model.compatible
feature:android.hardware.type.television
feature:android.hardware.usb.host
feature:android.hardware.vulkan.compute
feature:android.hardware.vulkan.level=1
feature:android.hardware.vulkan.version=4198400
feature:android.hardware.wifi
feature:android.hardware.wifi.direct
feature:android.hardware.wifi.passpoint
feature:android.software.activities_on_secondary_displays
feature:android.software.adoptable_storage
feature:android.software.app_enumeration
feature:android.software.app_widgets
feature:android.software.autofill
feature:android.software.backup
feature:android.software.cant_save_state
feature:android.software.cts
feature:android.software.device_admin
feature:android.software.file_based_encryption
feature:android.software.input_methods
feature:android.software.ipsec_tunnels
feature:android.software.leanback
feature:android.software.leanback_only
feature:android.software.live_tv
feature:android.software.opengles.deqp.level=132449025
feature:android.software.securely_removes_users
feature:android.software.verified_boot
feature:android.software.voice_recognizers
feature:android.software.vulkan.deqp.level=132449025
feature:android.software.webview
feature:com.google.android.feature.AMATI_EXPERIENCE
feature:com.google.android.feature.GLOBAL_ASSIST_TRIGGERING
feature:com.google.android.feature.GOOGLE_BUILD
feature:com.google.android.feature.GOOGLE_EXPERIENCE
feature:com.google.android.feature.tv.BBC
feature:droidlogic.software.netflix
feature:nrdp.modelgroup

**Comment by virresh** [comment]
Thanks for the list.

Our suspicions have turned out to be correct. Both faketouch and touchscreen are not supported on the newer versions. I'll do some changes in ADB version and drop them for testing in some time. Unfortunately experience with ADB has been pretty buggy and not reliable, but will add that as a stop gap at-least.

Will explore some alternate methods after the adb fix.

**Comment by virresh** [comment]
Hi @kokotas89 

Can you test this https://github.com/virresh/matvt/releases/download/v1.0.7-pre/matvt-app-release-1.0.7-adb-pre.apk with both the untrusted touch enabled and untrusted touch disabled?

```
adb shell settings put global block_untrusted_touches 0
```
and 

```
adb shell settings put global block_untrusted_touches 1
```

If this also fails, I am out of ideas on what can be done to make the mouse usable on devices that don't support faketouch...

**Comment by kokotas89** [comment]
Hello @virresh ! Yeees, this one actually worked. Clicking works just fine and scrolling does too but scrolling needs refining. It's very choppy and there's a lot of latency between the press of the button and the scroll. So if you hold the button for longer than required you will end a lot of choppy scroll sequences which take a while to finish. If you need logs let me know.

Blocking untrusted touches made no difference. On or off, matvt behaves the same.

**Comment by sujhran** [comment]
> Hi @kokotas89
> 
> Can you test this https://github.com/virresh/matvt/releases/download/v1.0.7-pre/matvt-app-release-1.0.7-adb-pre.apk with both the untrusted touch enabled and untrusted touch disabled?
> 
> ```
> adb shell settings put global block_untrusted_touches 0
> ```
> 
> and
> 
> ```
> adb shell settings put global block_untrusted_touches 1
> ```
> 
> If this also fails, I am out of ideas on what can be done to make the mouse usable on devices that don't support faketouch...

You did it @virresh 

I can confirm it is working for chromecast HD and 4K android 12 😀

MOUSE Speed and click is normal for me.
Scrolling have latency.
Good work 👏.

**Comment by virresh** [comment]
Great news.

Sadly cannot lower the latency of ADB by a large margin because it waits to receive the full input before executing it. This is so that we don't keep pressing the down button when we want continuous scroll. So I have to cut off the full swipe in chunks and cancel it when button is released, but by that time some scroll events have already been issued.


I'll try to find some time and see if a workaround is available. The worst case would require writing a custom ADB lib and seeing how much latency gain that gets, but it's a lot of code (involves rewriting lots of parts of adb, and I haven't worked with native libs in a long while). This could take a while though, no promises on when it'll be ready.

**Comment by kokotas89** [comment]
@virresh Hmm, maybe you could replace the scrolling mode with a different method then? For example, tvquickactions uses double click for a single swipe step. Not so much precision for small swipes but at least it feels smoother.

Also I noticed that on the twitch app, click still doesn't register except for highlighted items. I captured a log maybe it can help finetune something.

[logcat.txt](https://github.com/virresh/matvt/files/10258034/logcat.txt)

**Comment by virresh** [comment]
Interesting,
I'm not sure exactly what the issue is with twitch, not clear in current logs. I'll try the twitch app with emulator once though to see if this is replicable.

For the scroll, good idea, though it'll be very hard to scroll a very long list of items as it'd require much more button presses. I'll try to implement something similar as an alternate and provide a checkbox so users can choose what scroll behavior they want. Thanks!

**Comment by dikodahan** [comment]
I can also confirm a similar type of behavior on the Google Chromecast with ATV 12.
Unfortunately, on ATV 11 devices it is still not usable.

**Comment by TaniaAli268** [comment]
> 

Tysm for this fix @virresh 
I got an easy fix to this scroll issue ...

(Not sure how it works on other devices) 
Remove the scroll feature completely, that way its easier to switch between mouse & D-pad mode which offers a much better scrolling experience. 😃

**Comment by Moksh99** [comment]
Hi @virresh, how do I install this app with instructions mentioned above on Google chromecast 4k ? Specifically this part is not clear _with both the untrusted touch enabled and untrusted_  not sure how can I do this on Google chromecast device. Can you please provide more detailed instructions for people who doesn’t know much about command line and how to execute them ? Is there any other way from UI to enable/disable untrusted touch rather than executing commands.

**Comment by kokotas89** [comment]
@Moksh99 That adb command is not required. It was for testing purposes and at least to my experience it didn't make any difference. You should ignore that part for now.

To send adb commands to Chromecast you will need to setup adb wireless debugging. Sorry I can't provide details here, but it should be easy enough if you look up videos on YouTube.

**Comment by Moksh99** [comment]
Thanks @kokotas89 for reply. I installed v1.0.7 pre apk but it’s still the same issue. It’s not able to click an item which doesn’t have focus selected. Is this something that should have worked with pre version ?

**Comment by kokotas89** [comment]
@Moksh99 Did you do a clean installation?

**Comment by Moksh99** [comment]
> @Moksh99 Did you do a clean installation?

Yes, I did uninstall previous version and then install this new pre.apk and configured key 3 as mouse and tried scenario using chromecast 4k remote. This is latest chromecast 4k tv with Android 12.

**Comment by kokotas89** [comment]
@Moksh99 I see... I and two other users confirmed that the latest pre has scrolling and clicking working. But in my case when I tried matvt on twitch tv app, I could only click on highlighted streams. In every other app and Chromecast menu clicking worked as expected though.

Try setting up wireless adb debugging and provide a log.

**Comment by virresh** [comment]
+1 to everything @kokotas89 said.

Just wanted to check if you're using the adb pre release version ?

There were three variants in the pre-release post of which two don't work
I've removed the two that don't work to avoid confusion now.

**Comment by virresh** [comment]
Also on the scroll issue, I remember there was a community contribution which enabled bordered window and scroll on hitting border sides. Maybe that offers a better experience?

In case you try that, let me know the experience / improvements you think in a separate issue. Let's limit future discussions here to Android 12 issues :D

**Comment by sujhran** [comment]
> +1 to everything @kokotas89 said.
> 
> @Moksh99 Just wanted to check if you're using the adb pre release version ?
> 
> There were three variants in the pre-release post of which two don't work I've removed the two that don't work to avoid confusion now.
@Moksh99  uninstall previous version and install adb version. Mouse  Click will work.

https://github.com/virresh/matvt/releases/download/v1.0.7-pre/matvt-app-release-1.0.7-adb-pre.apk

**Comment by Moksh99** [comment]
Hi all,

I did uninstall previous version and again installed adb pre version using above link, but still same issue. It doesn’t click on the screen if the item doesn’t have focus selected. Not sure if I have to enable any other setting here. I did give special app permissions to display over other app and also enabled mouse toggle service as soon as I installed adb pre version. I did restart google tv once to see if it fixes the issue but still same behavior.

**Comment by MailYouLater** [comment]
Did you enable wireless adb debugging in Developer Options?
While the adb commands that were being discussed earlier may or may not be required, I'm fairly certain that the 'adb' test version of the app uses the loopback interface to send adb commands to the device for some functions.

**Comment by Moksh99** [comment]
Hi All, 

I did enable ADB debugging by following this article here - https://www.reddit.com/r/Chromecast/comments/s96moi/how_to_connect_to_ccwgtv_via_adb_using_only_wifi/

After I allowed debugging prompt and always allow first time, it didn’t work. Then I fired command - adb shell settings put global block_untrusted_touches 0 and adb shell settings put global block_untrusted_touches 1 one after another.

After this, mouse started clicking items, even if it’s not selected, woo hoo …. Scroll is however not working as expected, once scroll is enabled, it randomly scrolls and very weird behavior, so had to come out of it to use CCwGTv properly again.

Just for my own satisfaction, After all this, I disabled usb debugging option again and tried mouse operations but it didn’t work, same problem as before. Once I enabled usb debugging again, it started working. Once you enable, it will again ask for allow and check box as well which one has to allow and check the box.

*Summary* - use the adb-pre.apk shared by virresh but also make sure that usb debugging is enabled following the link below - https://www.reddit.com/r/Chromecast/comments/s96moi/how_to_connect_to_ccwgtv_via_adb_using_only_wifi/ and make sure you check the box and always allow, when it asks first time.

Thank you @virresh , @sujhran, @kokotas89 and @MailYouLater for guiding throughout this and special thanks to @virresh for enabling this app to users like me. Liked working with you all, cheers 👍🏻 Happy new year in advance !!!

**Comment by hellemmm** [comment]
Hi, i have same issue! I press left-click but nothing happens... But it is clickable with hardware mouse...
I use philips 65PUS8506/60 tv, android TV 11
I use MATVT 1.0.6
Any help?

**Comment by virresh** [comment]
@hellemmm 
Try MATVT v1.0.7-pre release - https://github.com/virresh/matvt/releases/download/v1.0.7-pre/matvt-app-release-1.0.7-adb-pre.apk

There are known issues on Android 11. See https://github.com/virresh/matvt/issues/28 for details.

**Comment by hellemmm** [comment]
Thnky you for fast reply!)
I have uninstalled 1.0.6, and uninstalled 1.0.7,  have tried 1.0.7 abd pre - same result..
Mouse clicking works sometimes, but not works in same cases with 1.0.6 version
What should i try next?
Thank you)
--
Отправлено из Mail.ru для Android суббота, 04 февраля 2023г., 08:21 +03:00 от Viresh Gupta  ***@***.*** :

**Comment by hellemmm** [comment]
Hi, once again!
I have tried restart and enabling developer options, usb debugging on, and now left click worked for 1 time.. it asked to allow debug from this device, and then 1 clock worked, and no more clicking works ... (((((
Also dpad become stucky sometimes.....
--
Отправлено из Mail.ru для Android суббота, 04 февраля 2023г., 08:21 +03:00 от Viresh Gupta  ***@***.*** :

**Comment by hellemmm** [comment]
Hi again) it now working!! Hooooooray!))))))
--
Отправлено из Mail.ru для Android суббота, 04 февраля 2023г., 08:21 +03:00 от Viresh Gupta  ***@***.*** :

**Comment by jtc1953** [comment]
Hi. After I got the MA VT v1.0.7-pre release installed I finally able to click with center button. (Google TV Android12). I have a suggestion.:   It would be nice with an option when the mouse pointer reach a side (border mode enabled)  automatically turns into scroll mode.
 Btw. Sometimes I get a promt to allow a RSA-key ???

**Comment by virresh** [comment]
> Btw. Sometimes I get a promt to allow a RSA-key ???

Yup, the RSA key prompt is because we use ADB under the hood.
[aquirozc](https://github.com/aquirozc) have contributed some improvements in how adb engine works, that should automatically save the RSA key.
If you're interested in trying that out, check out the interim release they created at 
 https://github.com/aquirozc/matvt/releases/download/v1.0.7-internal-pre-release05/MATVT.1.0.7-rs_adbserver_testbranch-main_lab-test25.apk

> It would be nice with an option when the mouse pointer reach a side

Noted.

**Comment by ferengialliance** [comment]
I'm a bit late to this party! Firstly thank you Virresh for your efforts!
I have been unable to get the 4k CCWGTV remote centre button to mouse click since the V12 upgrade.
I have read through the above and think I understand the issue, but am struggling with implementing the fix. 
I have installed  MATVT 1.07 3 times now (by creating a tinyurl and sticking it in downloader app) 
First I uninstalled v1.0.6
then tried  : matvt-app-release-1.0.7-pre2.apk this is the Android 12 version?
I enabled both permissions - didn't work - enabled USB debugging in developer options (i don't see any mention of ADB in there) - restarted - no joy. So I started again...
Same process with the ADB version and finally the lab test version above.

Is there something daft I am doing/not doing? Happy to be told I am :)

**Comment by ferengialliance** [comment]
Thanks @virresh I got around to installing the aquirozc version and all is good now , I may have missed the supplemental pop up for allowing usb debugging the first time I installed??, although I did it in developer settings manually 🤷🏽 - in any case it works! Good stuff!

**Comment by gracjan1983** [comment]
Hi, i have accidentally updated my Google TV chromecast from Android 12 to 14 today.
Click function is not working anymore. Mouse cursor is appearing, but no click. Any ideas how to fix it. I need a click urhently for one of my app. Thx
